name: API Test Workflow

on: [push, pull_request]

jobs:
  build:
    name: Run API tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: check tools
      run: |
        docker info
        python --version
        conda --version

    - name: Install and run sedge
      run: |  
        chmod +x scripts/*
        ./scripts/install-sedge.sh
        ./scripts/run-sedge.sh

    - name: Create python virtual ENV
      run: |
        conda env create -f environment.yml
        conda init bash
        source ~/.bashrc
        conda activate apitest      

    - name: Run Health check
      run: |
        conda activate apitest
        python -m utils.healthcheck

    - name: Run Verification Tests
      run: |
        conda activate apitest
        python -m pytest -m Regression tests/verification/verification_test.py -sv

