name: API Test Workflow

on: [push, pull_request]

jobs:
  build:
    name: Run API tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: check tools
      run: |
        docker info
        python --version
        conda --version

    - name: Install and run sedge
      run: |  
        chmod +x scripts/*
        ./scripts/install-sedge.sh
        ./scripts/run-sedge.sh