name: API Test Workflow

on: [push, pull_request]

jobs:
  build:
    name: Run API tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: check tools
      run: |
        docker info
        python --version
        conda --version

    - name: Install and run sedge
      run: |  
        chmod +x scripts/*
        ./scripts/install-sedge.sh
        ./scripts/run-sedge.sh

    - name: Create conda environment
      run: |
        $CONDA/bin/conda init && $CONDA/bin/conda env create --file environment.yml --name apitest

    - name: Run Health check
      run: |
        $CONDA/bin/conda activate apitest
        python -m utils.healthcheck

    - name: Run Verification Tests
      run: |
        $CONDA/bin/conda activate apitest
        python -m pytest -m Regression tests/verification/verification_test.py -sv

