name: Python Test

on: [push, pull_request]

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: docker buildx build --push --tag sedge-api-test .

  test:
    name: Run tests
    runs-on: ubuntu-latest

    container:
      image: sedge-api-test:latest
      options: --privileged

    env:
      ENV_NAME: apitest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Pull Docker image
      run: docker pull sedge-api-test:latest

    - name: Test in Docker container
      run: |
        service docker start
        conda init
        conda activate $ENV_NAME
        ./scripts/run-sedge.sh