name: Python Test

on: [push, pull_request]

jobs:
  login:
    name: Docker login
    runs-on: ubuntu-latest

    steps:
      - name: Docker login
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    needs: login

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          docker buildx build --push --tag ghcr.io/${{ github.actor }}/sedge-api-test:latest .
        env:
          GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
        options:
          privileged: true

  test:
    name: Run tests
    runs-on: ubuntu-latest
    needs: [build, login]

    steps:
      - name: Pull Docker image
        run: docker pull ghcr.io/${{ github.actor }}/sedge-api-test:latest

      - name: Test in Docker container
        run: |
          docker run --privileged -v /var/run/docker.sock:/var/run/docker.sock ghcr.io/${{ github.actor }}/sedge-api-test:latest /bin/bash -c "./scripts/run-sedge.sh && conda init && conda activate apitest && python -m utils.healthcheck && pytest -m Regression tests/verification/verification_test.py -sv --html=pytest-report/index.html --tracing on"